#!/usr/bin/env node

/*
  runner: node morph.js eva
*/

var lat = process.argv.slice(2)[0] || false;
var pdch = process.argv.slice(3)[0] || false;
// var util = require('util');

var sandhi = require('sandhi');
var u = sandhi.u;
var log = u.log;
var p = u.p;

var morph = require('./index');
var param = require('./lib/morph-param');

if (!lat) return log('?');

var opt = param(lat);
var samasa = opt.sa;
var lat = opt.lat;

log('_la_:', lat, '_sa_:', samasa);

log('S', samasa)
console.time('morph');

morph.run(samasa, null, function(res) {
    log('morph-0.3 res: ==============>>');
    p(res);
});

console.timeEnd('morph');
