#!/usr/bin/env node

/*
  runner:  ./morph run raTopasTaH OR  ./morph run रथोपस्थः
*/

var lat = process.argv.slice(2)[0] || false;

var program = require('commander');

program
    .version('0.4.0')
    .command('run [samasa]', 'run one morph request')
    .command('get [query]', 'get one word from MW')
    .command('list', 'list packages installed', {isDefault: true})
    .parse(process.argv);
