#!/usr/bin/env node

/*
  runner:  ./morph run raTopasTaH OR  ./morph run रथोपस्थः
*/

var lat = process.argv.slice(2)[0] || false;
// var pdch = process.argv.slice(3)[0] || false;
// var util = require('util');

// var sandhi = require('sandhi');
// var u = sandhi.u;
// var log = u.log;
// var p = u.p;

// var salita = require('salita-component');
var program = require('commander');

// if (!lat) return log('?');

// var samasa;
// if (/[a-zA-Z]/.test(lat[0])) {
//     samasa = salita.slp2sa(lat);
// } else {
//     samasa = lat;
//     lat = salita.sa2slp(samasa);
// }

// console.log('MORPH:::_la_:', lat, '_sa_:', samasa);

// console.time('morph');
// console.timeEnd('morph');

program
    .version('0.3.0')
    .command('run [samasa]', 'run one morph request')
    .command('get [query]', 'get one word from MW')
    .command('list', 'list packages installed', {isDefault: true})
    .parse(process.argv);
